# (C) 1992-2019 Intel Corporation.                            
# Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
# and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
# and/or other countries. Other marks and brands may be claimed as the property  
# of others. See Trademarks on intel.com for full list of Intel trademarks or    
# the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
# Your use of Intel Corporation's design tools, logic functions and other        
# software and tools, and its AMPP partner logic functions, and any output       
# files any of the foregoing (including device programming or simulation         
# files), and any associated documentation or information are expressly subject  
# to the terms and conditions of the Altera Program License Subscription         
# Agreement, Intel MegaCore Function License Agreement, or other applicable      
# license agreement, including, without limitation, that your use is for the     
# sole purpose of programming logic devices manufactured by Intel and sold by    
# Intel or its authorized distributors.  Please refer to the applicable          
# agreement for further details.                                                 

# TCL File Generated by Component Editor 12.1
# Wed Jun 13 15:44:31 PDT 2012
# DO NOT MODIFY


# 
# pcie_irq "PCI Express IRQ" v1.0
# null 2012.06.13.15:44:31
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module pcie_irq
# 
set_module_property NAME pcie_irq
set_module_property GROUP "Arria10 BSP Components"
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME "PCI Express IRQ"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pcie_irq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file pcie_irq.v VERILOG PATH pcie_irq.v
add_fileset_file msix_struct.v VERILOG PATH msix_struct.v
add_fileset_file msix_trans_gen.v VERILOG PATH msix_trans_gen.v
add_fileset_file irq_ena.v VERILOG PATH irq_ena.v
add_fileset_file irq_bridge.v VERILOG PATH irq_bridge.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pcie_irq
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file pcie_irq.v VERILOG PATH pcie_irq.v
add_fileset_file msix_struct.v VERILOG PATH msix_struct.v
add_fileset_file msix_trans_gen.v VERILOG PATH msix_trans_gen.v
add_fileset_file irq_ena.v VERILOG PATH irq_ena.v
add_fileset_file irq_bridge.v VERILOG PATH irq_bridge.v

# 
# parameters
# 


# 
# display items
# 


# 
# connection point MSIX_Structure_Slave
# 
add_interface MSIX_Structure_Slave avalon end
set_interface_property MSIX_Structure_Slave addressAlignment DYNAMIC
set_interface_property MSIX_Structure_Slave addressUnits SYMBOLS
set_interface_property MSIX_Structure_Slave associatedClock Clock
set_interface_property MSIX_Structure_Slave associatedReset Resetn
set_interface_property MSIX_Structure_Slave burstOnBurstBoundariesOnly false
set_interface_property MSIX_Structure_Slave explicitAddressSpan 0
set_interface_property MSIX_Structure_Slave holdTime 0
set_interface_property MSIX_Structure_Slave isMemoryDevice false
set_interface_property MSIX_Structure_Slave isNonVolatileStorage false
set_interface_property MSIX_Structure_Slave linewrapBursts false
set_interface_property MSIX_Structure_Slave maximumPendingReadTransactions 0
set_interface_property MSIX_Structure_Slave printableDevice false
set_interface_property MSIX_Structure_Slave readLatency 0
set_interface_property MSIX_Structure_Slave readWaitTime 1
set_interface_property MSIX_Structure_Slave setupTime 0
set_interface_property MSIX_Structure_Slave timingUnits Cycles
set_interface_property MSIX_Structure_Slave writeWaitTime 0
set_interface_property MSIX_Structure_Slave ENABLED true

add_interface_port MSIX_Structure_Slave MsixStructSChipSelect_i chipselect Input 1
add_interface_port MSIX_Structure_Slave MsixStructSAddress_i address Input 14
add_interface_port MSIX_Structure_Slave MsixStructSByteEnable_i byteenable Input 4
add_interface_port MSIX_Structure_Slave MsixStructSRead_i read Input 1
add_interface_port MSIX_Structure_Slave MsixStructSReadData_o readdata Output 32
add_interface_port MSIX_Structure_Slave MsixStructSWrite_i write Input 1
add_interface_port MSIX_Structure_Slave MsixStructSWriteData_i writedata Input 32
add_interface_port MSIX_Structure_Slave MsixStructSWaitRequest_o waitrequest Output 1

# 
# connection point IRQ Bridge Port
# 
add_interface IRQ_Read_Slave avalon end
set_interface_property IRQ_Read_Slave addressUnits WORDS
set_interface_property IRQ_Read_Slave associatedClock Clock
set_interface_property IRQ_Read_Slave associatedReset Resetn
set_interface_property IRQ_Read_Slave burstOnBurstBoundariesOnly false
set_interface_property IRQ_Read_Slave burstcountUnits WORDS
set_interface_property IRQ_Read_Slave explicitAddressSpan 0
set_interface_property IRQ_Read_Slave holdTime 0
set_interface_property IRQ_Read_Slave isMemoryDevice false
set_interface_property IRQ_Read_Slave isNonVolatileStorage false
set_interface_property IRQ_Read_Slave linewrapBursts false
set_interface_property IRQ_Read_Slave maximumPendingReadTransactions 0
set_interface_property IRQ_Read_Slave printableDevice false
set_interface_property IRQ_Read_Slave readLatency 0
set_interface_property IRQ_Read_Slave readWaitTime 1
set_interface_property IRQ_Read_Slave setupTime 0
set_interface_property IRQ_Read_Slave timingUnits Cycles
set_interface_property IRQ_Read_Slave writeWaitTime 0
set_interface_property IRQ_Read_Slave ENABLED true

add_interface_port IRQ_Read_Slave IrqRead_i read Input 1
add_interface_port IRQ_Read_Slave IrqReadData_o readdata Output 32

# 
# connection point IRQ Mask Ports
# 
add_interface IRQ_Mask_Slave avalon end
set_interface_property IRQ_Mask_Slave addressUnits WORDS
set_interface_property IRQ_Mask_Slave associatedClock Clock
set_interface_property IRQ_Mask_Slave associatedReset Resetn
set_interface_property IRQ_Mask_Slave burstOnBurstBoundariesOnly false
set_interface_property IRQ_Mask_Slave burstcountUnits WORDS
set_interface_property IRQ_Mask_Slave explicitAddressSpan 0
set_interface_property IRQ_Mask_Slave holdTime 0
set_interface_property IRQ_Mask_Slave isMemoryDevice false
set_interface_property IRQ_Mask_Slave isNonVolatileStorage false
set_interface_property IRQ_Mask_Slave linewrapBursts false
set_interface_property IRQ_Mask_Slave maximumPendingReadTransactions 0
set_interface_property IRQ_Mask_Slave printableDevice false
set_interface_property IRQ_Mask_Slave readLatency 0
set_interface_property IRQ_Mask_Slave readWaitTime 1
set_interface_property IRQ_Mask_Slave setupTime 0
set_interface_property IRQ_Mask_Slave timingUnits Cycles
set_interface_property IRQ_Mask_Slave writeWaitTime 0
set_interface_property IRQ_Mask_Slave ENABLED true

add_interface_port IRQ_Mask_Slave MaskWrite_i write Input 1
add_interface_port IRQ_Mask_Slave MaskWritedata_i writedata Input 32
add_interface_port IRQ_Mask_Slave MaskByteenable_i byteenable Input 4
add_interface_port IRQ_Mask_Slave MaskRead_i read Input 1
add_interface_port IRQ_Mask_Slave MaskReaddata_o readdata Output 32
add_interface_port IRQ_Mask_Slave MaskWaitrequest_o waitrequest Output 1


# 
# connection point IRQ_Gen_Master
# 
add_interface IRQ_Gen_Master avalon start
set_interface_property IRQ_Gen_Master addressUnits SYMBOLS
set_interface_property IRQ_Gen_Master associatedClock Clock
set_interface_property IRQ_Gen_Master associatedReset Resetn
set_interface_property IRQ_Gen_Master burstOnBurstBoundariesOnly false
set_interface_property IRQ_Gen_Master doStreamReads false
set_interface_property IRQ_Gen_Master doStreamWrites false
set_interface_property IRQ_Gen_Master linewrapBursts false
set_interface_property IRQ_Gen_Master readLatency 0
set_interface_property IRQ_Gen_Master ENABLED true

add_interface_port IRQ_Gen_Master MsixMWrite_o write Output 1
add_interface_port IRQ_Gen_Master MsixMAddress_o address Output 64
add_interface_port IRQ_Gen_Master MsixMWriteData_o writedata Output 32
add_interface_port IRQ_Gen_Master MsixMByteEnable_o byteenable Output 4
add_interface_port IRQ_Gen_Master MsixMWaitRequest_i waitrequest Input 1


# 
# connection point MSIX_Interface
# 
add_interface MSIX_Interface conduit end
set_interface_property MSIX_Interface associatedClock ""
set_interface_property MSIX_Interface associatedReset ""
set_interface_property MSIX_Interface ENABLED true

add_interface_port MSIX_Interface MsixIntfc_i msix_intfc Input 16


# 
# connection point MSI_Interface
# 
add_interface MSI_Interface conduit end
set_interface_property MSI_Interface associatedClock ""
set_interface_property MSI_Interface associatedReset ""
set_interface_property MSI_Interface ENABLED true

add_interface_port MSI_Interface MsiIntfc_i msi_intfc Input 82


# 
# connection point INTX_Interface
# 
add_interface INTX_Interface conduit end
set_interface_property INTX_Interface associatedClock ""
set_interface_property INTX_Interface associatedReset ""
set_interface_property INTX_Interface ENABLED true

add_interface_port INTX_Interface IntxReq_o intx_req Output 1
add_interface_port INTX_Interface IntxAck_i intx_ack Input 1


# 
# connection point Clock
# 
add_interface Clock clock end
set_interface_property Clock clockRate 0
set_interface_property Clock ENABLED true

add_interface_port Clock Clk_i clk Input 1


# 
# connection point Resetn
# 
add_interface Resetn reset end
set_interface_property Resetn associatedClock Clock
set_interface_property Resetn synchronousEdges DEASSERT
set_interface_property Resetn ENABLED true

add_interface_port Resetn Rstn_i reset_n Input 1


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint IRQ_Gen_Master
set_interface_property interrupt_receiver associatedClock Clock
set_interface_property interrupt_receiver associatedReset Resetn
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true

add_interface_port interrupt_receiver Irq_i irq Input 32

